version: '3'
services:

  mongo:
      image: mongo
      container_name: mongo
      ports:
        - "27017:27017"
      networks:
        - app-network
        - mongo

  mongo_seed:
    image: mongo
    container_name: mongo_seed
    links:
      - mongo
    volumes:
      - ./dump/:/mongo-seed/dump/
      - ./server/src/assets/scripts/import-mongodata.sh:/mongo-seed/import-mongodata.sh
    command:
      /mongo-seed/import-mongodata.sh
    networks:
      - mongo

  server:
      build: ./server
      container_name: server
      env_file: ./server/.env
      ports:
        - "5000:5000"
      volumes:
        - ./server/:/server/
        - /server/node_modules
        - /server/build
      depends_on:
        - mongo
      environment:
        - MONGO_HOSTNAME=mongo
        - MONGO_PORT=27017
        - MONGO_DB=TheCountOfMoney
      networks:
        - app-network

  app:
    build: ./client
    container_name: app
    volumes:
      - ./client/:/application
      - /application/node_modules
    stdin_open: true
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
      driver: bridge
  mongo:
      driver: bridge

volumes:
  node_modules:
  web-root:
    driver: local
